; Script generated by the HM NIS Edit Script Wizard.

; HM NIS Edit Wizard helper defines
!define PRODUCT_NAME "Captcha Solver"
!define PRODUCT_VERSION "0.2.1-alpha"
!define PRODUCT_PUBLISHER "Justin Iven"
!define PRODUCT_DIR_REGKEY "Software\Microsoft\Windows\CurrentVersion\App Paths\main.exe"
!define PRODUCT_UNINST_KEY "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PRODUCT_NAME}"
!define PRODUCT_UNINST_ROOT_KEY "HKLM"

; MUI 1.67 compatible ------
!include "MUI.nsh"

; MUI Settings
!define MUI_ABORTWARNING
!define MUI_ICON "C:\Users\jmueller\OneDrive - Sorba EDV AG\Privat\pythonProjects\captcha-solver-ui\logos\install.ico"
!define MUI_UNICON "C:\Users\jmueller\OneDrive - Sorba EDV AG\Privat\pythonProjects\captcha-solver-ui\logos\uninstall.ico"

; Welcome page
!insertmacro MUI_PAGE_WELCOME
; Directory page
!insertmacro MUI_PAGE_DIRECTORY
; Instfiles page
!insertmacro MUI_PAGE_INSTFILES
; Finish page
!define MUI_FINISHPAGE_RUN "$INSTDIR\main.exe"
!insertmacro MUI_PAGE_FINISH

; Uninstaller pages
!insertmacro MUI_UNPAGE_INSTFILES

; Language files
!insertmacro MUI_LANGUAGE "German"

; MUI end ------

Name "${PRODUCT_NAME} ${PRODUCT_VERSION}"
OutFile "CaptchaSolver-setup.exe"
InstallDir "$PROGRAMFILES\Captcha Solver"
InstallDirRegKey HKLM "${PRODUCT_DIR_REGKEY}" ""
ShowInstDetails show
ShowUnInstDetails show

Section "Hauptgruppe" SEC01
  SetOutPath "$INSTDIR"
  SetOverwrite ifnewer
  File "C:\Users\jmueller\OneDrive - Sorba EDV AG\Privat\pythonProjects\captcha-solver-ui\messages.json"
  File "C:\Users\jmueller\OneDrive - Sorba EDV AG\Privat\pythonProjects\captcha-solver-ui\main.exe"
  CreateDirectory "$SMPROGRAMS\Captcha Solver"
  CreateShortCut "$SMPROGRAMS\Captcha Solver\Captcha Solver.lnk" "$INSTDIR\main.exe"
  CreateShortCut "$DESKTOP\Captcha Solver.lnk" "$INSTDIR\main.exe"
  File "C:\Users\jmueller\OneDrive - Sorba EDV AG\Privat\pythonProjects\captcha-solver-ui\icon.ico"
  File "C:\Users\jmueller\OneDrive - Sorba EDV AG\Privat\pythonProjects\captcha-solver-ui\GetData.exe"
  File "C:\Users\jmueller\OneDrive - Sorba EDV AG\Privat\pythonProjects\captcha-solver-ui\conf.ini"
  File "C:\Users\jmueller\OneDrive - Sorba EDV AG\Privat\pythonProjects\captcha-solver-ui\chromedriver.exe"
SectionEnd

Section -AdditionalIcons
  CreateShortCut "$SMPROGRAMS\Captcha Solver\Uninstall.lnk" "$INSTDIR\uninst.exe"
SectionEnd

Section -Post
  WriteUninstaller "$INSTDIR\uninst.exe"
  WriteRegStr HKLM "${PRODUCT_DIR_REGKEY}" "" "$INSTDIR\main.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayName" "$(^Name)"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "UninstallString" "$INSTDIR\uninst.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayIcon" "$INSTDIR\main.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayVersion" "${PRODUCT_VERSION}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "Publisher" "${PRODUCT_PUBLISHER}"
SectionEnd


Function un.onUninstSuccess
  HideWindow
  MessageBox MB_ICONINFORMATION|MB_OK "$(^Name) wurde erfolgreich deinstalliert."
FunctionEnd

Function un.onInit
  MessageBox MB_ICONQUESTION|MB_YESNO|MB_DEFBUTTON2 "Möchten Sie $(^Name) und alle seinen Komponenten deinstallieren?" IDYES +2
  Abort
FunctionEnd

Section Uninstall
  Delete "$INSTDIR\uninst.exe"
  Delete "$INSTDIR\chromedriver.exe"
  Delete "$INSTDIR\conf.ini"
  Delete "$INSTDIR\GetData.exe"
  Delete "$INSTDIR\icon.ico"
  Delete "$INSTDIR\main.exe"
  Delete "$INSTDIR\messages.json"

  Delete "$SMPROGRAMS\Captcha Solver\Uninstall.lnk"
  Delete "$DESKTOP\Captcha Solver.lnk"
  Delete "$SMPROGRAMS\Captcha Solver\Captcha Solver.lnk"

  RMDir "$SMPROGRAMS\Captcha Solver"
  RMDir "$INSTDIR"

  DeleteRegKey ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}"
  DeleteRegKey HKLM "${PRODUCT_DIR_REGKEY}"
  SetAutoClose true
SectionEnd